# -*- coding: utf-8 -*-
"""Exercícios.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Zkbon1AUru3DuJS3oRlUGHxQLFcHJOB
"""

#Crie um programa que leia algo pelo teclado 
# e mostre na tela o seu tipo primitivo e todas as 
# informações possíveis sobre ele.

inf = input('Digite algo pro favor. ')
print(type(inf))
print('Essa informação é alfanumérica?', inf.isalnum())
print('Essa informação é alfabética?',inf.isalpha())
print('Essa informação é decimal?',inf.isdecimal())
print('Essa informação é um digito?',inf.isdigit())
print('Essa informação é indentificável?',inf.isidentifier())
print('Essa informação é uma palavra que tem só letras minúsculas?',inf.islower())
print('Essa informação é numérica?',inf.isnumeric())
print('Essa informação é copiável?',inf.isprintable())
print('Essa informação é uma palavra que tem só letras maiúsculas', inf.isupper())
inf1 = int(input('Digite algo inteiro por favor. '))
print(type(inf1))
inf2 = float(input('Digite algo por favor. '))
print(type(inf2))
inf3 = bool(input('Digite algo por favor'))
print(type(inf3))
