# -*- coding: utf-8 -*-
"""Exercícios.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Zkbon1AUru3DuJS3oRlUGHxQLFcHJOB
"""

n1 = float(input('Digite o primeiro número: '))
n2 = float(input('Digite o segundo número: '))
#print('A soma entre', n1, 'e', n2, 'vale',(n1+n2)) Forma antiga de programação
print('A soma entre {} e {} vale {}'. format(n1, n2, (n1+n2)))
