ng = float(input('Digite um número: '))
print('A tabuada desse número é:')
print()
print('{} x  1 = {}'.format(ng,(ng*1)))
print('{} x  2 = {}'.format(ng,(ng*2)))
print('{} x  3 = {}'.format(ng,(ng*3)))
print('{} x  4 = {}'.format(ng,(ng*4)))
print('{} x  5 = {}'.format(ng,(ng*5)))
print('{} x  6 = {}'.format(ng,(ng*6)))
print('{} x  7 = {}'.format(ng,(ng*7)))
print('{} x  8 = {}'.format(ng,(ng*8)))
print('{} x  9 = {}'.format(ng,(ng*9)))
print('{} x 10 = {}'.format(ng,(ng*10)))
